# Generated by Django 5.1.15 on 2026-07-30 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_project_budget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_committed_date", models.DateField()),
                ("new_committed_date", models.DateField()),
                ("client_agreement_reference", models.TextField()),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_extensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_extensions",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_extension",
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="SchedulePhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("site_visit", "Site visit / requirement assessment"),
                            ("boq_prep", "Engineering / BOQ preparation"),
                            ("procurement", "Procurement"),
                            ("construction", "Construction"),
                        ],
                        max_length=24,
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("planned_start", models.DateField(blank=True, null=True)),
                ("planned_end", models.DateField()),
                ("actual_start", models.DateField(blank=True, null=True)),
                ("actual_end", models.DateField(blank=True, null=True)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_phases",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_phase",
                "ordering": ["project", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="PhaseDateChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_end", models.DateField(blank=True, null=True)),
                ("new_end", models.DateField()),
                ("reason", models.TextField(blank=True)),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_changes",
                        to="projects.schedulephase",
                    ),
                ),
            ],
            options={
                "db_table": "phase_date_change",
                "ordering": ["-at"],
            },
        ),
        migrations.AddConstraint(
            model_name="schedulephase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("planned_start__isnull", True),
                    ("planned_end__gte", models.F("planned_start")),
                    _connector="OR",
                ),
                name="phase_ends_after_it_starts",
            ),
        ),
    ]
