# Generated by Django 5.1.15 on 2026-07-30 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_boqline_section_boqline_sl_no_alter_boqline_item"),
        ("engineering", "0001_initial"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("gstin", models.CharField(blank=True, max_length=32)),
                ("address", models.TextField(blank=True)),
                ("contact_name", models.CharField(blank=True, max_length=128)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("trades", models.JSONField(blank=True, default=list)),
                ("is_empanelled", models.BooleanField(default=False)),
                ("payment_terms", models.CharField(blank=True, max_length=128)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "vendor",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProcurementRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("BOQ_RELEASE", "BOQ revision released"),
                            ("SITE_REQUISITION", "Raised on site"),
                            ("FABRICATION_SHORTFALL", "Fabrication raw material"),
                        ],
                        max_length=32,
                    ),
                ),
                ("number", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("awaiting_approval", "Awaiting Project Manager approval"),
                            ("approved", "Approved"),
                            ("held", "Held for re-review"),
                            ("sourced", "Sourced"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("is_site_raised", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("hold_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "boq_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procurement_requests",
                        to="engineering.boqrevision",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procurement_requests",
                        to="core.project",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procurement_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "procurement_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcurementRequestLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("uom", models.CharField(default="nos", max_length=32)),
                ("required_by", models.DateField(blank=True, null=True)),
                (
                    "boq_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procurement_lines",
                        to="core.boqline",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.item",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="procurement.procurementrequest",
                    ),
                ),
            ],
            options={
                "db_table": "procurement_request_line",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("number", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("awaiting_approval", "Awaiting Purchase Manager approval"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("expected_delivery", models.DateField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="core.project",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="procurement.procurementrequest",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="procurement.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("uom", models.CharField(default="nos", max_length=32)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "boq_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="po_lines",
                        to="core.boqline",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.item",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="po_lines",
                        to="sales.lot",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="procurement.purchaseorder",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order_line",
            },
        ),
        migrations.CreateModel(
            name="PoAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_qty", models.DecimalField(decimal_places=4, max_digits=18)),
                ("new_qty", models.DecimalField(decimal_places=4, max_digits=18)),
                ("reason", models.TextField()),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="procurement.purchaseorderline",
                    ),
                ),
            ],
            options={
                "db_table": "po_amendment",
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="Rfq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued to vendors"),
                            ("comparing", "Quotes in, comparing"),
                            ("awarded", "Awarded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("closes_at", models.DateField(blank=True, null=True)),
                ("min_vendors_waived_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfqs",
                        to="procurement.procurementrequest",
                    ),
                ),
            ],
            options={
                "db_table": "rfq",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RfqVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "rfq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendors",
                        to="procurement.rfq",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfq_invitations",
                        to="procurement.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "rfq_vendor",
            },
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("awarded_rate", models.DecimalField(decimal_places=2, max_digits=18)),
                ("awarded_qty", models.DecimalField(decimal_places=4, max_digits=18)),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                ("comparison_snapshot", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "awarded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="awards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="awards",
                        to="procurement.procurementrequestline",
                    ),
                ),
                (
                    "rfq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="awards",
                        to="procurement.rfq",
                    ),
                ),
                (
                    "winning_vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="awards",
                        to="procurement.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "award",
            },
        ),
        migrations.CreateModel(
            name="VendorRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=256)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=18)),
                ("uom", models.CharField(default="nos", max_length=32)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_rates",
                        to="core.item",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="procurement.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_rate",
            },
        ),
        migrations.CreateModel(
            name="RfqQuoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quoted_rate", models.DecimalField(decimal_places=2, max_digits=18)),
                ("quoted_qty", models.DecimalField(decimal_places=4, max_digits=18)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("terms", models.CharField(blank=True, max_length=256)),
                ("notes", models.TextField(blank=True)),
                (
                    "request_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="procurement.procurementrequestline",
                    ),
                ),
                (
                    "rfq_vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_lines",
                        to="procurement.rfqvendor",
                    ),
                ),
            ],
            options={
                "db_table": "rfq_quote_line",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rfq_vendor", "request_line"),
                        name="uniq_quote_per_line",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="rfqvendor",
            constraint=models.UniqueConstraint(
                fields=("rfq", "vendor"), name="uniq_rfq_vendor"
            ),
        ),
        migrations.AddConstraint(
            model_name="award",
            constraint=models.UniqueConstraint(
                fields=("rfq", "request_line"), name="uniq_award_per_line"
            ),
        ),
    ]
