# Generated by Django 5.1.15 on 2026-07-30 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_boqline_drawing_reference_boqline_lot_boqline_notes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoqRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("revision_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sections_signed", "Sections signed off"),
                            ("released", "Released"),
                            ("sent_back", "Sent back"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("prepared_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("sent_back_reason", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boq_revisions",
                        to="core.project",
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="released_boq_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="engineering.boqrevision",
                    ),
                ),
            ],
            options={
                "db_table": "boq_revision",
                "ordering": ["project", "-revision_number"],
            },
        ),
        migrations.CreateModel(
            name="BoqSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discipline",
                    models.CharField(
                        choices=[("goods", "Goods"), ("service", "Service")],
                        max_length=16,
                    ),
                ),
                ("signed_off_at", models.DateTimeField(blank=True, null=True)),
                ("is_not_applicable", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boq_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="engineering.boqrevision",
                    ),
                ),
                (
                    "signed_off_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signed_boq_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "boq_section",
            },
        ),
        migrations.CreateModel(
            name="ReconciliationOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("uom", models.CharField(blank=True, max_length=32)),
                (
                    "previous_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "new_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "delta",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "committed_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "received_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "excess_received",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "order_reduction",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("new", "New line"),
                            ("increased", "Quantity increased"),
                            ("decreased_uncommitted", "Decreased, nothing committed"),
                            ("decreased_ordered", "Decreased, already ordered"),
                            ("decreased_received", "Decreased, already received"),
                            ("unchanged", "Unchanged"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            (
                                "request_delta",
                                "Raise procurement request for the delta",
                            ),
                            ("reduce_draft", "Reduce or remove the draft request line"),
                            (
                                "amend_order",
                                "Amend or cancel the outstanding order quantity",
                            ),
                            (
                                "return_queue",
                                "Route to the return / redeployment queue",
                            ),
                            ("none", "No action"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_removal", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "boq_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_outcomes",
                        to="core.boqline",
                    ),
                ),
                (
                    "previous_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.boqline",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_outcomes",
                        to="engineering.boqrevision",
                    ),
                ),
            ],
            options={
                "db_table": "reconciliation_outcome",
                "ordering": ["revision", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="boqrevision",
            constraint=models.UniqueConstraint(
                fields=("project", "revision_number"), name="uniq_project_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="boqsection",
            constraint=models.UniqueConstraint(
                fields=("revision", "discipline"), name="uniq_revision_discipline"
            ),
        ),
    ]
