# Generated by Django 5.1.15 on 2026-07-30 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_boqline_section_boqline_sl_no_alter_boqline_item"),
        ("procurement", "0001_initial"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("number", models.CharField(max_length=64, unique=True)),
                ("scope_description", models.TextField()),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("uom", models.CharField(default="nos", max_length=32)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("awaiting_approval", "Awaiting Purchase Manager approval"),
                            ("issued", "Issued to subcontractor"),
                            ("complete", "Complete"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "boq_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_orders",
                        to="core.boqline",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_orders",
                        to="sales.lot",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_orders",
                        to="core.project",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_orders",
                        to="procurement.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "service_order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "percent_complete",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "quantity_done",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("photographs", models.JSONField(blank=True, default=list)),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="subcontracts.serviceorder",
                    ),
                ),
            ],
            options={
                "db_table": "service_progress",
                "ordering": ["-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=64, unique=True)),
                ("source_type", models.CharField(max_length=64)),
                ("source_id", models.BigIntegerField()),
                ("bill_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("paid", "Paid"),
                            ("held", "Held"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_bills",
                        to="sales.lot",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_bills",
                        to="core.project",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="procurement.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_bill",
                "ordering": ["-bill_date"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("running_bill_number", models.PositiveIntegerField()),
                (
                    "certified_quantity",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "certified_value",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("is_final", models.BooleanField(default=False)),
                ("certified_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                (
                    "certified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="subcontracts.serviceorder",
                    ),
                ),
            ],
            options={
                "db_table": "service_certification",
                "ordering": ["service_order", "running_bill_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("service_order", "running_bill_number"),
                        name="uniq_running_bill",
                    )
                ],
            },
        ),
    ]
