# Generated by Django 5.1.15 on 2026-07-30 14:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_type", models.CharField(max_length=64)),
                ("document_id", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("sent_back", "Sent back"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "approval_request",
            },
        ),
        migrations.CreateModel(
            name="AdminOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=128)),
                ("entity_id", models.BigIntegerField()),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admin_override",
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("send_back", "Send back"),
                        ],
                        max_length=16,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="platform_core.approvalrequest",
                    ),
                ),
            ],
            options={
                "db_table": "approval_action",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_type", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                (
                    "threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "required_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_rules",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "db_table": "approval_rule",
                "ordering": ["document_type", "sequence"],
            },
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="platform_core.approvalrule",
            ),
        ),
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=128)),
                ("entity_id", models.BigIntegerField()),
                ("action", models.CharField(max_length=64)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_entry",
            },
        ),
        migrations.CreateModel(
            name="CommitmentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_type", models.CharField(max_length=64)),
                ("document_id", models.BigIntegerField()),
                ("qty_delta", models.DecimalField(decimal_places=4, max_digits=18)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "boq_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commitments",
                        to="core.boqline",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commitments",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "db_table": "commitment_entry",
            },
        ),
        migrations.CreateModel(
            name="CostEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MATERIAL", "Material"),
                            ("FABRICATION", "Fabrication"),
                            ("SUBCONTRACT", "Subcontract"),
                            ("SITE_EXPENSE", "Site expense"),
                            ("STOCK_IN", "Stock transferred in"),
                            ("STOCK_OUT", "Stock transferred out"),
                            ("REVENUE", "Revenue"),
                        ],
                        max_length=32,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("source_type", models.CharField(max_length=64)),
                ("source_id", models.BigIntegerField()),
                ("effective_date", models.DateField()),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "boq_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_entries",
                        to="core.boqline",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_entries",
                        to="core.project",
                    ),
                ),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversals",
                        to="platform_core.costentry",
                    ),
                ),
            ],
            options={
                "db_table": "cost_entry",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(blank=True, max_length=128)),
                ("title", models.CharField(max_length=256)),
                ("body", models.TextField(blank=True)),
                ("entity_type", models.CharField(blank=True, max_length=128)),
                ("entity_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=128)),
                ("payload", models.JSONField(default=dict)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("failed", "Failed, will retry"),
                            ("dead", "Dead-lettered"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "outbox_event",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="outbox_even_status_966362_idx",
                    ),
                    models.Index(
                        fields=["event_name"], name="outbox_even_event_n_9f7744_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unit_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("source_type", models.CharField(max_length=64)),
                ("source_id", models.BigIntegerField()),
                ("effective_at", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves_out",
                        to="core.location",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves",
                        to="core.item",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves_in",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "db_table": "stock_move",
            },
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["document_type", "document_id", "status"],
                name="approval_re_documen_a5dea7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditentry",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="audit_entry_entity__202b83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="commitmententry",
            index=models.Index(
                fields=["boq_line"], name="commitment__boq_lin_c1875f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commitmententry",
            index=models.Index(
                fields=["document_type", "document_id"],
                name="commitment__documen_49ff6f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="commitmententry",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_delta", Decimal("0")), _negated=True),
                name="commitment_delta_nonzero",
            ),
        ),
        migrations.AddIndex(
            model_name="costentry",
            index=models.Index(
                fields=["project", "category", "effective_date"],
                name="cost_entry_project_2eab8e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="costentry",
            index=models.Index(fields=["lot_id"], name="cost_entry_lot_id_009f8f_idx"),
        ),
        migrations.AddIndex(
            model_name="costentry",
            index=models.Index(
                fields=["source_type", "source_id"],
                name="cost_entry_source__afefdd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmove",
            index=models.Index(
                fields=["item", "to_location"], name="stock_move_item_id_37fcae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmove",
            index=models.Index(
                fields=["item", "from_location"], name="stock_move_item_id_cd7cca_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmove",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", Decimal("0"))),
                name="stock_move_qty_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmove",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_location__isnull", True),
                    ("to_location__isnull", True),
                    _negated=True,
                ),
                name="stock_move_has_endpoint",
            ),
        ),
    ]
