# Generated by Django 5.1.15 on 2026-07-30 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_boqline_drawing_reference_boqline_lot_boqline_notes_and_more"),
        ("platform_core", "0002_append_only_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmove",
            name="boq_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_moves",
                to="core.boqline",
            ),
        ),
    ]
