# Generated by Django 5.1.15 on 2026-07-30 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_project_client_project_date_end_project_date_start_and_more"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boqline",
            name="drawing_reference",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="boqline",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boq_lines",
                to="sales.lot",
            ),
        ),
        migrations.AddField(
            model_name="boqline",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="boqline",
            name="previous_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_lines",
                to="core.boqline",
            ),
        ),
    ]
