# Generated by Django 5.1.15 on 2026-07-30 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_boqline_drawing_reference_boqline_lot_boqline_notes_and_more"),
        ("engineering", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boqline",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="engineering.boqsection",
            ),
        ),
        migrations.AddField(
            model_name="boqline",
            name="sl_no",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="boqline",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boq_lines",
                to="core.item",
            ),
        ),
    ]
