# Generated by Django 5.1.15 on 2026-07-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testsupport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="demodocument",
            name="status",
            field=models.CharField(default="draft", max_length=32),
        ),
    ]
