# Generated by Django 5.1.15 on 2026-07-30 16:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_boqline_section_boqline_sl_no_alter_boqline_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discrepancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("debit_note_raised", "Debit note raised"),
                            ("replacement_requested", "Replacement requested"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=24,
                    ),
                ),
                ("debit_note_number", models.CharField(blank=True, max_length=64)),
                ("holds_vendor_bill", models.BooleanField(default=True)),
                ("raised_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "discrepancy",
            },
        ),
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=64, unique=True)),
                ("received_qty", models.DecimalField(decimal_places=4, max_digits=18)),
                ("received_at", models.DateTimeField()),
                ("vendor_challan", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recorded", "Recorded, awaiting verification"),
                            ("verified", "Verified"),
                            ("discrepancy", "Discrepancy logged"),
                        ],
                        default="recorded",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "goods_receipt",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=64, unique=True)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("reason", models.TextField()),
                ("debit_note_number", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent to vendor"),
                            ("credited", "Credit received"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "material_return",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceiptVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified_at", models.DateTimeField()),
                ("accepted_qty", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "rejected_qty",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("discrepancy_notes", models.TextField(blank=True)),
                ("photographs", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "receipt_verification",
            },
        ),
        migrations.CreateModel(
            name="ExpectedReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expected_qty", models.DecimalField(decimal_places=4, max_digits=18)),
                ("expected_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaited"),
                            ("partial", "Partly received"),
                            ("complete", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expected_receipts",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "db_table": "expected_receipt",
                "ordering": ["expected_date", "id"],
            },
        ),
    ]
