# Generated by Django 5.1.15 on 2026-07-30 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_boqline_section_boqline_sl_no_alter_boqline_item"),
        ("inventory", "0001_initial"),
        ("procurement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expectedreceipt",
            name="purchase_order_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expected_receipts",
                to="procurement.purchaseorderline",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="expected_receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="inventory.expectedreceipt",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="core.location",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="purchase_order_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="procurement.purchaseorderline",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="received_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts_recorded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="materialreturn",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="materialreturn",
            name="goods_receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="returns",
                to="inventory.goodsreceipt",
            ),
        ),
        migrations.AddField(
            model_name="materialreturn",
            name="purchase_order_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="returns",
                to="procurement.purchaseorderline",
            ),
        ),
        migrations.AddField(
            model_name="receiptverification",
            name="goods_receipt",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verification",
                to="inventory.goodsreceipt",
            ),
        ),
        migrations.AddField(
            model_name="receiptverification",
            name="verified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discrepancy",
            name="verification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discrepancies",
                to="inventory.receiptverification",
            ),
        ),
    ]
