# Generated by Django 5.1.15 on 2026-07-30 14:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("site_visit", "Site visit"),
                            ("estimating", "Estimating"),
                            ("quoted", "Quoted"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                (
                    "rough_order_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("expected_close", models.DateField(blank=True, null=True)),
                ("won_at", models.DateTimeField(blank=True, null=True)),
                ("lost_at", models.DateTimeField(blank=True, null=True)),
                ("lost_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "opportunities",
                "db_table": "opportunity",
            },
        ),
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visited_at", models.DateTimeField()),
                ("findings", models.TextField(blank=True)),
                (
                    "rough_estimate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
            ],
            options={
                "db_table": "site_visit",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("meeting", "Meeting"),
                            ("email", "Email"),
                            ("follow_up", "Follow up"),
                        ],
                        default="follow_up",
                        max_length=16,
                    ),
                ),
                ("due_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activity",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("enquiry", "Site enquiry"),
                            ("referral", "Referral"),
                            ("tender", "Tender notice"),
                        ],
                        default="enquiry",
                        max_length=16,
                    ),
                ),
                ("client_name", models.CharField(max_length=256)),
                ("contact_name", models.CharField(blank=True, max_length=128)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("site_location", models.CharField(blank=True, max_length=256)),
                ("work_type", models.CharField(blank=True, max_length=64)),
                ("territory", models.CharField(blank=True, max_length=64)),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("assigned", "Assigned"),
                            ("qualified", "Qualified"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lead",
            },
        ),
        migrations.CreateModel(
            name="LeadAssignmentRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_type", models.CharField(blank=True, max_length=64)),
                ("territory", models.CharField(blank=True, max_length=64)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assign_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lead_assignment_rule",
                "ordering": ["sequence"],
            },
        ),
    ]
